<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/06/07 04:49:44

return array(
'default' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cajab',
  'username' => 'root',
  'password' => NULL,
  'name' => 'default',
)),);
