all:
  layout: menu
pagarServicioSuccess:
  javascripts: [moment.min.js,pagarServicio.js]
pagarServicioClienteSuccess:
  javascripts: [moment.min.js,pagarServicioCliente.js]
movimientosCajaSuccess:
  javascripts: [moment.min.js,movimientosCaja.js]
