<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConceptosCobro', 'default');

/**
 * BaseConceptosCobro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_servicio
 * @property string $concepto
 * @property date $fecha_registro
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getIdServicio()     Returns the current record's "id_servicio" value
 * @method string         getConcepto()       Returns the current record's "concepto" value
 * @method date           getFechaRegistro()  Returns the current record's "fecha_registro" value
 * @method ConceptosCobro setId()             Sets the current record's "id" value
 * @method ConceptosCobro setIdServicio()     Sets the current record's "id_servicio" value
 * @method ConceptosCobro setConcepto()       Sets the current record's "concepto" value
 * @method ConceptosCobro setFechaRegistro()  Sets the current record's "fecha_registro" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConceptosCobro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conceptos_cobro');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_servicio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('concepto', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fecha_registro', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
	    $this->hasColumn('estatus', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}