<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rutas', 'default');

/**
 * BaseRutas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $capacidad
 * @property string $chofer
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getCapacidad() Returns the current record's "capacidad" value
 * @method string  getChofer()    Returns the current record's "chofer" value
 * @method Rutas   setId()        Sets the current record's "id" value
 * @method Rutas   setCapacidad() Sets the current record's "capacidad" value
 * @method Rutas   setChofer()    Sets the current record's "chofer" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRutas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rutas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('capacidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('chofer', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}