<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proveedores', 'default');

/**
 * BaseProveedores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $telefono
 * @property string $direccion
 * @property string $email
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method string      getNombre()    Returns the current record's "nombre" value
 * @method string      getTelefono()  Returns the current record's "telefono" value
 * @method string      getDireccion() Returns the current record's "direccion" value
 * @method string      getEmail()     Returns the current record's "email" value
 * @method Proveedores setId()        Sets the current record's "id" value
 * @method Proveedores setNombre()    Sets the current record's "nombre" value
 * @method Proveedores setTelefono()  Sets the current record's "telefono" value
 * @method Proveedores setDireccion() Sets the current record's "direccion" value
 * @method Proveedores setEmail()     Sets the current record's "email" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProveedores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedores');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('telefono', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}