<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AsignacionTrasporte', 'default');

/**
 * BaseAsignacionTrasporte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_alumno
 * @property integer $id_ruta
 * @property timestamp $fecha_inicio
 * @property timestamp $fecha_fin
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getIdAlumno()     Returns the current record's "id_alumno" value
 * @method integer             getIdRuta()       Returns the current record's "id_ruta" value
 * @method timestamp           getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method timestamp           getFechaFin()     Returns the current record's "fecha_fin" value
 * @method AsignacionTrasporte setId()           Sets the current record's "id" value
 * @method AsignacionTrasporte setIdAlumno()     Sets the current record's "id_alumno" value
 * @method AsignacionTrasporte setIdRuta()       Sets the current record's "id_ruta" value
 * @method AsignacionTrasporte setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method AsignacionTrasporte setFechaFin()     Sets the current record's "fecha_fin" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsignacionTrasporte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asignacion_trasporte');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_alumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ruta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}