<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListaCicloEscolar', 'default');

/**
 * BaseListaCicloEscolar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcicloescolar
 * @property date $fechainicio
 * @property date $fechatermino
 * @property string $estatus
 * @property string $seccion
 * @property string $nombre
 * @property string $prefijomatricula
 * @property integer $idseccion
 * 
 * @method integer           getIdcicloescolar()   Returns the current record's "idcicloescolar" value
 * @method date              getFechainicio()      Returns the current record's "fechainicio" value
 * @method date              getFechatermino()     Returns the current record's "fechatermino" value
 * @method string            getEstatus()          Returns the current record's "estatus" value
 * @method string            getSeccion()          Returns the current record's "seccion" value
 * @method string            getNombre()           Returns the current record's "nombre" value
 * @method string            getPrefijomatricula() Returns the current record's "prefijomatricula" value
 * @method integer           getIdseccion()        Returns the current record's "idseccion" value
 * @method Listacicloescolar setIdcicloescolar()   Sets the current record's "idcicloescolar" value
 * @method Listacicloescolar setFechainicio()      Sets the current record's "fechainicio" value
 * @method Listacicloescolar setFechatermino()     Sets the current record's "fechatermino" value
 * @method Listacicloescolar setEstatus()          Sets the current record's "estatus" value
 * @method Listacicloescolar setSeccion()          Sets the current record's "seccion" value
 * @method Listacicloescolar setNombre()           Sets the current record's "nombre" value
 * @method Listacicloescolar setPrefijomatricula() Sets the current record's "prefijomatricula" value
 * @method Listacicloescolar setIdseccion()        Sets the current record's "idseccion" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaCicloEscolar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ListaCicloEscolar');
        $this->hasColumn('idcicloescolar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fechainicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fechatermino', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estatus', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('seccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('prefijomatricula', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('idseccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}