<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServiciosCliente', 'default');

/**
 * BaseServiciosCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_servicio
 * @property integer $id_alumno
 * @property integer $id_cliente
 * @property timestamp $fecha_registro
 * @property string $usuario_registro
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getIdServicio()       Returns the current record's "id_servicio" value
 * @method integer          getIdAlumno()         Returns the current record's "id_alumno" value
 * @method integer          getIdCliente()        Returns the current record's "id_cliente" value
 * @method timestamp        getFechaRegistro()    Returns the current record's "fecha_registro" value
 * @method string           getUsuarioRegistro()  Returns the current record's "usuario_registro" value
 * @method ServiciosCliente setId()               Sets the current record's "id" value
 * @method ServiciosCliente setIdServicio()       Sets the current record's "id_servicio" value
 * @method ServiciosCliente setIdAlumno()         Sets the current record's "id_alumno" value
 * @method ServiciosCliente setIdCliente()        Sets the current record's "id_cliente" value
 * @method ServiciosCliente setFechaRegistro()    Sets the current record's "fecha_registro" value
 * @method ServiciosCliente setUsuarioRegistro()  Sets the current record's "usuario_registro" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiciosCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicios_cliente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_servicio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_alumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_registro', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('usuario_registro', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}