<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServicioCliente', 'default');

/**
 * BaseServicioCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_servicio
 * @property integer $id_alumno
 * @property integer $id_cliente
 * @property timestamp $fecha_registro
 * @property string $usuario_registro
 * @property integer $tipo_cliente
 * @property integer $estatus
 * 
 * @method integer         getId()               Returns the current record's "id" value
 * @method integer         getIdServicio()       Returns the current record's "id_servicio" value
 * @method integer         getIdAlumno()         Returns the current record's "id_alumno" value
 * @method integer         getIdCliente()        Returns the current record's "id_cliente" value
 * @method timestamp       getFechaRegistro()    Returns the current record's "fecha_registro" value
 * @method string          getUsuarioRegistro()  Returns the current record's "usuario_registro" value
 * @method integer         getTipoCliente()      Returns the current record's "tipo_cliente" value
 * @method integer         getEstatus()          Returns the current record's "estatus" value
 * @method ServicioCliente setId()               Sets the current record's "id" value
 * @method ServicioCliente setIdServicio()       Sets the current record's "id_servicio" value
 * @method ServicioCliente setIdAlumno()         Sets the current record's "id_alumno" value
 * @method ServicioCliente setIdCliente()        Sets the current record's "id_cliente" value
 * @method ServicioCliente setFechaRegistro()    Sets the current record's "fecha_registro" value
 * @method ServicioCliente setUsuarioRegistro()  Sets the current record's "usuario_registro" value
 * @method ServicioCliente setTipoCliente()      Sets the current record's "tipo_cliente" value
 * @method ServicioCliente setEstatus()          Sets the current record's "estatus" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicioCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio_cliente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_servicio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_alumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_registro', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('usuario_registro', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('tipo_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatus', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}