<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServicioPago', 'default');

/**
 * BaseServicioPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_servicio
 * @property integer $id_cliente
 * @property float $monto
 * @property timestamp $fecha_pago
 * @property integer $tipo_cliente
 * @property integer $id_alumno
 * @property integer $usuario_registro
 * @property timestamp $fecha_registro
 * @property integer $tipo_pago
 * @property string $forma_pago
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method integer      getIdServicio()       Returns the current record's "id_servicio" value
 * @method integer      getIdCliente()        Returns the current record's "id_cliente" value
 * @method float        getMonto()            Returns the current record's "monto" value
 * @method timestamp    getFechaPago()        Returns the current record's "fecha_pago" value
 * @method integer      getTipoCliente()      Returns the current record's "tipo_cliente" value
 * @method integer      getIdAlumno()         Returns the current record's "id_alumno" value
 * @method integer      getUsuarioRegistro()  Returns the current record's "usuario_registro" value
 * @method timestamp    getFechaRegistro()    Returns the current record's "fecha_registro" value
 * @method integer      getTipoPago()         Returns the current record's "tipo_pago" value
 * @method string       getFormaPago()        Returns the current record's "forma_pago" value
 * @method ServicioPago setId()               Sets the current record's "id" value
 * @method ServicioPago setIdServicio()       Sets the current record's "id_servicio" value
 * @method ServicioPago setIdCliente()        Sets the current record's "id_cliente" value
 * @method ServicioPago setMonto()            Sets the current record's "monto" value
 * @method ServicioPago setFechaPago()        Sets the current record's "fecha_pago" value
 * @method ServicioPago setTipoCliente()      Sets the current record's "tipo_cliente" value
 * @method ServicioPago setIdAlumno()         Sets the current record's "id_alumno" value
 * @method ServicioPago setUsuarioRegistro()  Sets the current record's "usuario_registro" value
 * @method ServicioPago setFechaRegistro()    Sets the current record's "fecha_registro" value
 * @method ServicioPago setTipoPago()         Sets the current record's "tipo_pago" value
 * @method ServicioPago setFormaPago()        Sets the current record's "forma_pago" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicioPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio_pago');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_servicio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monto', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_pago', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipo_cliente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_alumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_registro', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_registro', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipo_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('forma_pago', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
         $this->hasColumn('id_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
          $this->hasColumn('descuento', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
		  $this->hasColumn('estatus', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}