<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoriaServicio', 'default');

/**
 * BaseCategoriaServicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $categoria
 * @property integer $estatus
 * @property integer $tipo
 * @property string $descripcion
 * 
 * @method integer           getId()          Returns the current record's "id" value
 * @method string            getCategoria()   Returns the current record's "categoria" value
 * @method integer           getEstatus()     Returns the current record's "estatus" value
 * @method integer           getTipo()        Returns the current record's "tipo" value
 * @method string            getDescripcion() Returns the current record's "descripcion" value
 * @method CategoriaServicio setId()          Sets the current record's "id" value
 * @method CategoriaServicio setCategoria()   Sets the current record's "categoria" value
 * @method CategoriaServicio setEstatus()     Sets the current record's "estatus" value
 * @method CategoriaServicio setTipo()        Sets the current record's "tipo" value
 * @method CategoriaServicio setDescripcion() Sets the current record's "descripcion" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriaServicio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria_servicio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('categoria', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('estatus', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}