<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListaAlumnoB', 'default');

/**
 * BaseListaAlumnoB
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcolonia
 * @property string $nombre
 * @property string $appat
 * @property string $apmat
 * @property string $cuentaactiva
 * @property string $rfc
 * @property string $curp
 * @property string $direccion
 * @property string $celular
 * @property string $telefono
 * @property string $email
 * @property integer $idalumno
 * @property integer $idcicloescolar
 * @property integer $idgrado
 * @property integer $idgrupo
 * @property string $matricula
 * @property date $fechaingreso
 * @property string $alumnoactivo
 * @property string $motivoseparacion
 * @property date $fechabaja
 * @property date $fechanacimiento
 * @property string $sexo
 * @property string $escuelaprocedencia
 * @property string $usuarioactivo
 * @property string $nombrecompleto
 * @property string $nombrecicloescolar
 * @property string $nombregrado
 * @property string $nombregrupo
 * @property string $nombreseccion
 * @property string $gradopuro
 * @property integer $idseccion
 * @property string $seccion
 * @property string $grado
 * @property string $tiposeccion
 * 
 * @method integer      getIdcolonia()          Returns the current record's "idcolonia" value
 * @method string       getNombre()             Returns the current record's "nombre" value
 * @method string       getAppat()              Returns the current record's "appat" value
 * @method string       getApmat()              Returns the current record's "apmat" value
 * @method string       getCuentaactiva()       Returns the current record's "cuentaactiva" value
 * @method string       getRfc()                Returns the current record's "rfc" value
 * @method string       getCurp()               Returns the current record's "curp" value
 * @method string       getDireccion()          Returns the current record's "direccion" value
 * @method string       getCelular()            Returns the current record's "celular" value
 * @method string       getTelefono()           Returns the current record's "telefono" value
 * @method string       getEmail()              Returns the current record's "email" value
 * @method integer      getIdalumno()           Returns the current record's "idalumno" value
 * @method integer      getIdcicloescolar()     Returns the current record's "idcicloescolar" value
 * @method integer      getIdgrado()            Returns the current record's "idgrado" value
 * @method integer      getIdgrupo()            Returns the current record's "idgrupo" value
 * @method string       getMatricula()          Returns the current record's "matricula" value
 * @method date         getFechaingreso()       Returns the current record's "fechaingreso" value
 * @method string       getAlumnoactivo()       Returns the current record's "alumnoactivo" value
 * @method string       getMotivoseparacion()   Returns the current record's "motivoseparacion" value
 * @method date         getFechabaja()          Returns the current record's "fechabaja" value
 * @method date         getFechanacimiento()    Returns the current record's "fechanacimiento" value
 * @method string       getSexo()               Returns the current record's "sexo" value
 * @method string       getEscuelaprocedencia() Returns the current record's "escuelaprocedencia" value
 * @method string       getUsuarioactivo()      Returns the current record's "usuarioactivo" value
 * @method string       getNombrecompleto()     Returns the current record's "nombrecompleto" value
 * @method string       getNombrecicloescolar() Returns the current record's "nombrecicloescolar" value
 * @method string       getNombregrado()        Returns the current record's "nombregrado" value
 * @method string       getNombregrupo()        Returns the current record's "nombregrupo" value
 * @method string       getNombreseccion()      Returns the current record's "nombreseccion" value
 * @method string       getGradopuro()          Returns the current record's "gradopuro" value
 * @method integer      getIdseccion()          Returns the current record's "idseccion" value
 * @method string       getSeccion()            Returns the current record's "seccion" value
 * @method string       getGrado()              Returns the current record's "grado" value
 * @method string       getTiposeccion()        Returns the current record's "tiposeccion" value
 * @method Listaalumnob setIdcolonia()          Sets the current record's "idcolonia" value
 * @method Listaalumnob setNombre()             Sets the current record's "nombre" value
 * @method Listaalumnob setAppat()              Sets the current record's "appat" value
 * @method Listaalumnob setApmat()              Sets the current record's "apmat" value
 * @method Listaalumnob setCuentaactiva()       Sets the current record's "cuentaactiva" value
 * @method Listaalumnob setRfc()                Sets the current record's "rfc" value
 * @method Listaalumnob setCurp()               Sets the current record's "curp" value
 * @method Listaalumnob setDireccion()          Sets the current record's "direccion" value
 * @method Listaalumnob setCelular()            Sets the current record's "celular" value
 * @method Listaalumnob setTelefono()           Sets the current record's "telefono" value
 * @method Listaalumnob setEmail()              Sets the current record's "email" value
 * @method Listaalumnob setIdalumno()           Sets the current record's "idalumno" value
 * @method Listaalumnob setIdcicloescolar()     Sets the current record's "idcicloescolar" value
 * @method Listaalumnob setIdgrado()            Sets the current record's "idgrado" value
 * @method Listaalumnob setIdgrupo()            Sets the current record's "idgrupo" value
 * @method Listaalumnob setMatricula()          Sets the current record's "matricula" value
 * @method Listaalumnob setFechaingreso()       Sets the current record's "fechaingreso" value
 * @method Listaalumnob setAlumnoactivo()       Sets the current record's "alumnoactivo" value
 * @method Listaalumnob setMotivoseparacion()   Sets the current record's "motivoseparacion" value
 * @method Listaalumnob setFechabaja()          Sets the current record's "fechabaja" value
 * @method Listaalumnob setFechanacimiento()    Sets the current record's "fechanacimiento" value
 * @method Listaalumnob setSexo()               Sets the current record's "sexo" value
 * @method Listaalumnob setEscuelaprocedencia() Sets the current record's "escuelaprocedencia" value
 * @method Listaalumnob setUsuarioactivo()      Sets the current record's "usuarioactivo" value
 * @method Listaalumnob setNombrecompleto()     Sets the current record's "nombrecompleto" value
 * @method Listaalumnob setNombrecicloescolar() Sets the current record's "nombrecicloescolar" value
 * @method Listaalumnob setNombregrado()        Sets the current record's "nombregrado" value
 * @method Listaalumnob setNombregrupo()        Sets the current record's "nombregrupo" value
 * @method Listaalumnob setNombreseccion()      Sets the current record's "nombreseccion" value
 * @method Listaalumnob setGradopuro()          Sets the current record's "gradopuro" value
 * @method Listaalumnob setIdseccion()          Sets the current record's "idseccion" value
 * @method Listaalumnob setSeccion()            Sets the current record's "seccion" value
 * @method Listaalumnob setGrado()              Sets the current record's "grado" value
 * @method Listaalumnob setTiposeccion()        Sets the current record's "tiposeccion" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaAlumnoB extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ListaAlumnoB');
        $this->hasColumn('idcolonia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('appat', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('apmat', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cuentaactiva', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rfc', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('curp', 'string', 25, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('celular', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('idalumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcicloescolar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idgrado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idgrupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('matricula', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('fechaingreso', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('alumnoactivo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('motivoseparacion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('fechabaja', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fechanacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('escuelaprocedencia', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('usuarioactivo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('nombrecompleto', 'string', 252, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 252,
             ));
        $this->hasColumn('nombrecicloescolar', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('nombregrado', 'string', 96, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 96,
             ));
        $this->hasColumn('nombregrupo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('nombreseccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('gradopuro', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('idseccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('seccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('grado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('tiposeccion', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('bajasolo', 'string', 1, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 12,
        ));
        
        $this->hasColumn('direccionbajada', 'string', '', array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' =>'',
        ));
        
        $this->hasColumn('personarecibe', 'string', 100, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 100,
        ));
        
        $this->hasColumn('observaciones', 'string', '', array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => '',
        ));
        $this->hasColumn('dia', 'string', '', array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => '',
        ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}