<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CronEjecutado', 'default');

/**
 * BaseCronEjecutado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo
 * @property string $fecha_ejecucion
 * 
 * @method integer       getId()     Returns the current record's "id" value
 * @method string        getTipo() Returns the current record's "nombre" value
 * @method string        getFechaEjecucion()  Returns the current record's "grado" value
 * @method AlumnoPruebas setId()     Sets the current record's "id" value
 * @method AlumnoPruebas setTipo() Sets the current record's "nombre" value
 * @method AlumnoPruebas setFechaEjecucion()  Sets the current record's "grado" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCronEjecutado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cron_ejecutado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
       $this->hasColumn('fecha_ejecucion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}