<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AlumnoPruebas', 'default');

/**
 * BaseAlumnoPruebas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $grado
 * @property string $grupo
 * @property string $ciclo
 * 
 * @method integer       getId()     Returns the current record's "id" value
 * @method string        getNombre() Returns the current record's "nombre" value
 * @method string        getGrado()  Returns the current record's "grado" value
 * @method string        getGrupo()  Returns the current record's "grupo" value
 * @method string        getCiclo()  Returns the current record's "ciclo" value
 * @method AlumnoPruebas setId()     Sets the current record's "id" value
 * @method AlumnoPruebas setNombre() Sets the current record's "nombre" value
 * @method AlumnoPruebas setGrado()  Sets the current record's "grado" value
 * @method AlumnoPruebas setGrupo()  Sets the current record's "grupo" value
 * @method AlumnoPruebas setCiclo()  Sets the current record's "ciclo" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumnoPruebas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno_pruebas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('grado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('grupo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('ciclo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}