<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BaseListaAlumnoB', 'default');

/**
 * BaseListaAlumnoB
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_alumno
 * @property integer $id_ruta
 * @property timestamp $fecha_inicio
 * @property timestamp $fecha_fin
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getIdAlumno()     Returns the current record's "id_alumno" value
 * @method integer             getIdRuta()       Returns the current record's "id_ruta" value
 * @method timestamp           getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method timestamp           getFechaFin()     Returns the current record's "fecha_fin" value
 * @method AsignacionTrasporte setId()           Sets the current record's "id" value
 * @method AsignacionTrasporte setIdAlumno()     Sets the current record's "id_alumno" value
 * @method AsignacionTrasporte setIdRuta()       Sets the current record's "id_ruta" value
 * @method AsignacionTrasporte setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method AsignacionTrasporte setFechaFin()     Sets the current record's "fecha_fin" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaAlumnoB extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listaalumnob');
        $this->hasColumn('idalumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcolonia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('appat', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('apmat', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('cuentaactiva', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('rfc', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('curp', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        
        $this->hasColumn('direccion', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('celular', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('telefono', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        
        $this->hasColumn('email', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('idcicloescolar', 'integer', 4, array(
        		'type' => 'integer',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 4,
        ));
        $this->hasColumn('idgrado', 'integer', 4, array(
        		'type' => 'integer',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 4,
        ));
        $this->hasColumn('idgrupo', 'integer', 4, array(
        		'type' => 'integer',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 4,
        ));

        $this->hasColumn('matricula', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('fechaingreso', 'timestamp', 25, array(
        		'type' => 'timestamp',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 25,
        ));

        $this->hasColumn('alumnoactivo', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));

        $this->hasColumn('motivoseparacion', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('fechabaja', 'timestamp', 25, array(
        		'type' => 'timestamp',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 25,
        ));
        $this->hasColumn('fechanacimiento', 'timestamp', 25, array(
        		'type' => 'timestamp',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 25,
        ));
        $this->hasColumn('sexo', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('escuelaprocedencia', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('usuarioactivo', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('nombrecompleto', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('NombreCicloEscolar', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('NombreGrado', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('NombreGrupo', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('NombreSeccion', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        
        $this->hasColumn('GradoPuro', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('idseccion', 'integer', 4, array(
        		'type' => 'integer',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 4,
        ));
        $this->hasColumn('seccion', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('grado', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
        $this->hasColumn('TipoSeccion', 'string', 200, array(
        		'type' => 'string',
        		'fixed' => 0,
        		'unsigned' => false,
        		'primary' => false,
        		'notnull' => false,
        		'autoincrement' => false,
        		'length' => 200,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}