<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListaRuta', 'default');

/**
 * BaseListaRuta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_alumno
 * @property integer $id_ruta
 * @property timestamp $fecha
 * @property integer $estatus
 * @property integer $estatus_s
 * @property integer $estatus_b
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method integer   getIdAlumno()  Returns the current record's "id_alumno" value
 * @method integer   getIdRuta()    Returns the current record's "id_ruta" value
 * @method timestamp getFecha()     Returns the current record's "fecha" value
 * @method integer   getEstatus()   Returns the current record's "estatus" value
 * @method integer   getEstatusS()  Returns the current record's "estatus_s" value
 * @method integer   getEstatusB()  Returns the current record's "estatus_b" value
 * @method ListaRuta setId()        Sets the current record's "id" value
 * @method ListaRuta setIdAlumno()  Sets the current record's "id_alumno" value
 * @method ListaRuta setIdRuta()    Sets the current record's "id_ruta" value
 * @method ListaRuta setFecha()     Sets the current record's "fecha" value
 * @method ListaRuta setEstatus()   Sets the current record's "estatus" value
 * @method ListaRuta setEstatusS()  Sets the current record's "estatus_s" value
 * @method ListaRuta setEstatusB()  Sets the current record's "estatus_b" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaRuta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lista_ruta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_alumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ruta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estatus', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatus_s', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatus_b', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}