<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'default');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_completo
 * @property string $usuario
 * @property string $password
 * @property integer $rol
 * @property integer $estatus
 * @property timestamp $fecha_creacion
 * @property integer $id_empleado
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getNombreCompleto()  Returns the current record's "nombre_completo" value
 * @method string    getUsuario()         Returns the current record's "usuario" value
 * @method string    getPassword()        Returns the current record's "password" value
 * @method integer   getRol()             Returns the current record's "rol" value
 * @method integer   getEstatus()         Returns the current record's "estatus" value
 * @method timestamp getFechaCreacion()   Returns the current record's "fecha_creacion" value
 * @method integer   getIdEmpleado()      Returns the current record's "id_empleado" value
 * @method Usuario   setId()              Sets the current record's "id" value
 * @method Usuario   setNombreCompleto()  Sets the current record's "nombre_completo" value
 * @method Usuario   setUsuario()         Sets the current record's "usuario" value
 * @method Usuario   setPassword()        Sets the current record's "password" value
 * @method Usuario   setRol()             Sets the current record's "rol" value
 * @method Usuario   setEstatus()         Sets the current record's "estatus" value
 * @method Usuario   setFechaCreacion()   Sets the current record's "fecha_creacion" value
 * @method Usuario   setIdEmpleado()      Sets the current record's "id_empleado" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_completo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('usuario', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('password', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('rol', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatus', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_empleado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}