<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListaGrupo', 'default');

/**
 * BaseListaGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idgrupo
 * @property string $nombre
 * @property string $grado
 * @property string $ciclo
 * @property string $profesor
 * @property string $seccion
 * @property integer $idgrado
 * @property integer $idcuenta
 * @property integer $idcicloescolar
 * @property integer $idseccion
 * @property string $oficial
 * 
 * @method integer    getIdgrupo()        Returns the current record's "idgrupo" value
 * @method string     getNombre()         Returns the current record's "nombre" value
 * @method string     getGrado()          Returns the current record's "grado" value
 * @method string     getCiclo()          Returns the current record's "ciclo" value
 * @method string     getProfesor()       Returns the current record's "profesor" value
 * @method string     getSeccion()        Returns the current record's "seccion" value
 * @method integer    getIdgrado()        Returns the current record's "idgrado" value
 * @method integer    getIdcuenta()       Returns the current record's "idcuenta" value
 * @method integer    getIdcicloescolar() Returns the current record's "idcicloescolar" value
 * @method integer    getIdseccion()      Returns the current record's "idseccion" value
 * @method string     getOficial()        Returns the current record's "oficial" value
 * @method Listagrupo setIdgrupo()        Sets the current record's "idgrupo" value
 * @method Listagrupo setNombre()         Sets the current record's "nombre" value
 * @method Listagrupo setGrado()          Sets the current record's "grado" value
 * @method Listagrupo setCiclo()          Sets the current record's "ciclo" value
 * @method Listagrupo setProfesor()       Sets the current record's "profesor" value
 * @method Listagrupo setSeccion()        Sets the current record's "seccion" value
 * @method Listagrupo setIdgrado()        Sets the current record's "idgrado" value
 * @method Listagrupo setIdcuenta()       Sets the current record's "idcuenta" value
 * @method Listagrupo setIdcicloescolar() Sets the current record's "idcicloescolar" value
 * @method Listagrupo setIdseccion()      Sets the current record's "idseccion" value
 * @method Listagrupo setOficial()        Sets the current record's "oficial" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ListaGrupo');
        $this->hasColumn('idgrupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 250, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('grado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('ciclo', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('profesor', 'string', 252, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 252,
             ));
        $this->hasColumn('seccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('idgrado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcuenta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcicloescolar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idseccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('oficial', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}