<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HorariosRutas', 'default');

/**
 * BaseHorariosRutas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_ruta
 * @property string $dia
 * 
 * @method integer       getId()      Returns the current record's "id" value
 * @method integer       getIdRuta()  Returns the current record's "id_ruta" value
 * @method string        getDia()     Returns the current record's "dia" value
 * @method HorariosRutas setId()      Sets the current record's "id" value
 * @method HorariosRutas setIdRuta()  Sets the current record's "id_ruta" value
 * @method HorariosRutas setDia()     Sets the current record's "dia" value
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHorariosRutas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('horarios_rutas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ruta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dia', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}