<?php

/**
 * AlumnoPruebasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlumnoPruebasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlumnoPruebasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlumnoPruebas');
    }
}