<?php

/**
 * AsignacionTrasporteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionTrasporteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionTrasporteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignacionTrasporte');
    }
}