<?php

/**
 * ClientesExternosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientesExternosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientesExternosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientesExternos');
    }
}