<?php

/**
 * ConceptosCobroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConceptosCobroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConceptosCobroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConceptosCobro');
    }
}