<?php

/**
 * CronEjecutadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CronEjecutadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlumnoPruebasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CronEjecutado');
    }
}