<?php

/**
 * EgresosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EgresosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EgresosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Egresos');
    }
}