<?php

/**
 * HorarioRutaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HorarioRutaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HorarioRutaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HorarioRuta');
    }
}