<?php

/**
 * HorariosRutasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HorariosRutasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HorariosRutasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HorariosRutas');
    }
}