<?php

/**
 * ListacicloescolarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListacicloescolarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListacicloescolarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Listacicloescolar');
    }
}