<?php

/**
 * ListaCicloEscolarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListaCicloEscolarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListaCicloEscolarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListaCicloEscolar');
    }
}