<?php

/**
 * ListaAlumnoBTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListaAlumnoBTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListaAlumnoBTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListaAlumnoBTable');
    }
}