<?php

/**
 * ListagrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListagrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListagrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Listagrupo');
    }
}