<?php

/**
 * PagosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pagos');
    }
}