<?php

/**
 * ProveedoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProveedoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProveedoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proveedores');
    }
}