<?php

/**
 * RutasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RutasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RutasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rutas');
    }
}