<?php

/**
 * ServicioClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicioClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicioClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicioCliente');
    }
}