<?php

/**
 * ServiciosClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiciosClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiciosClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiciosCliente');
    }
}