<?php

/**
 * ServicioPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicioPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicioPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicioPago');
    }
}