<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    puntoveta
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario
{
     public function isPasswordValid($password)

  {

    //return ($this->getPassword() === MD5($password));
   return ($this->getPassword() === $password);

  }

  

  public function isActive()

  {

    return ((int)$this->getEstatus() === 1);

  }

  

 public function isExpired()

  {

  	$exp_date = $this->getExpira();

  	$today_date = time();

  	

  	return ($today_date > strtotime($exp_date));

  }

}