# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: estadoCuenta, action: serviciosEstatus }  
clientes_externos:
  url:   /clientes-externos
  param: { module: clientes, action: index }
clientes_modificar:
  url:   /clientes-modificar
  param: { module: clientes, action: clientesModificar }
agregar_clientes:
  url:   /agregar-clientes
  param: { module: clientes, action: agregarNuevoCliente }

proveedores_list:
  url:   /proveedores-list
  param: { module: egresos, action: proveedores }
proveedor_modificar:
  url:   /proveedor-modificar
  param: { module: egresos, action: ProveedorModificar }
agregar_proveedor:
  url:   /agregar-proveedor
  param: { module: egresos, action: agregarNuevoProveedor }

egresos_list:
  url:   /egresos-list
  param: { module: egresos, action: index }
agregar_egresos:
  url:   /agregar-egresos
  param: { module: egresos, action: agregarEgreso }  
  
catalogo_conceptos_pago:
  url:   /catalogo-conceptosPago
  param: { module: egresos, action: catalogoConceptosPago } 

egresos_imprimir:
  url:   /imprimir-egresos
  param: { module: egresos, action: imprimirEgresos } 
egresos_excel:
  url:   /excel-egresos
  param: { module: egresos, action: excelEgresos }     
#ParametroS
empleados_lista:
  url:   /empleados
  param: { module: parametros, action: index }
empleados_agregar:
  url:   /nuevo-empleados
  param: { module: parametros, action: agregarEmpleado }
empleados_actualizar:
  url:   /actualizar-empleados
  param: { module: parametros, action: actualizarEmpleado }
empleados_detalle:
  url:   /detalle-empleados
  param: { module: parametros, action: detalleEmpleado }
empleados_password:
  url:   /empleados-password
  param: { module: parametros, action: nuevaPassword }

#categorias
categorias-list:
  url:   /categorias-list
  param: { module: parametros, action: categoriasList }
categorias_agregar:
  url:   /categorias-agregar
  param: { module: parametros, action: agregarCategoria } 
categorias_modificar:
  url:   /categorias-modificar
  param: { module: parametros, action: modificarCategoria } 

#conceptos de cobro
conceptos-list:
  url:   /conceptos-list
  param: { module: egresos, action: getConceptosList }
conceptos_agregar:
  url:   /conceptos-agregar
  param: { module: egresos, action: agregarConceptos } 
conceptos_modificar:
  url:   /conceptos-modificar
  param: { module: egresos, action: conceptoModificar } 

  #SERVICIOS  *CORONEL*


servicios:
  url:   /servicios
  param: { module: servicios, action: index }
servicios_guardar_nuevo_servicio:
  url:   /servicios_guardar_nuevo_servicio
  param: { module: servicios, action: guardarNuevoServicio }
servicios_listado_servicios:
  url:   /servicios_listado_servicios
  param: { module: servicios, action: listadoServicios }
servicios_asignar_servicios:
  url:   /servicios_asignar_servicios
  param: { module: servicios, action: asignarServicios }
servicios_eliminar_servicio:
  url:   /servicios_eliminar_servicio
  param: { module: servicios, action: eliminarServicio }
servicios_listado_servicios_vigentes:
  url:   /servicios_listado_servicios_vigentes
  param: { module: servicios, action: listadoServiciosVigentes }
servicios_listado_categorias_servicios:
  url:   /servicios_listado_categorias_servicios
  param: { module: servicios, action: listadoCategoriasServicios }
servicios_listado_alumnos:
  url:   /servicios_listado_alumnos
  param: { module: servicios, action: listadoAlumnos } 
servicios_listado_clientes_externos:
  url:   /servicios_listado_clientes_externos
  param: { module: servicios, action: listadoClientesExternos }
servicios_asignar_alumnos_servicio:
  url:   /servicios_asignar_alumnos_servicio
  param: { module: servicios, action: asignarAlumnosServicio }
servicios_asignar_clientes_servicio:
  url:   /servicios_asignar_clientes_servicio
  param: { module: servicios, action: asignarClientesServicio }    
servicios_asignados_a_servicio:
  url:   /servicios_asignados_a_servicio
  param: { module: servicios, action: asignadosAServicio }    
servicios_cambiar_estatus_servicio_cliente:
  url:   /servicios_cambiar_estatus_servicio_cliente
  param: { module: servicios, action:  cambiarEstatusServicioCliente } 
servicios_imprimir_asignados_a_servicio:
  url:   /servicios_imprimir_asignados_a_servicio
  param: { module: servicios, action:  imprimirAsignadosAServicio }    
servicios_asignar_alumno_servicio:
 url:   /servicios_asignar_alumno_servicio
 param: { module: servicios, action:  asignarAlumnoServicio }    


#Fin SERVICIOS

#TRANSPORTE  *CORONEL*


transporte_horarios:
  url:   /transporte_horarios
  param: { module: transporte, action: horarios }
transporte_rutas:
  url:   /transporte_rutas
  param: { module: transporte, action: rutas }
transporte_listas_rutas:
  url:   /transporte_listas_rutas
  param: { module: transporte, action: listasRutas }
transporte_listado_rutas:
  url:   /transporte_listado_rutas
  param: { module: transporte, action: listadoRutas }
transporte_listado_rutas_activas:
  url:   /transporte_listado_rutas_activas
  param: { module: transporte, action: listadoRutasActivas }
transporte_guardar_ruta:
  url:   /transporte_guardar_ruta
  param: { module: transporte, action: guardarRuta }  
transporte_eliminar_ruta:
  url:   /transporte_eliminar_ruta
  param: { module: transporte, action: eliminarRuta } 
transporte_horarios_alumnos:
  url:   /transporte_horarios_alumnos
  param: { module: transporte, action: horariosAlumnos } 
transporte_cambiar_horario_alumno:
  url:   /transporte_cambiar_horario_alumno
  param: { module: transporte, action: cambiarHorarioAlumno }   
transporte_alumnos_por_ruta_dia:
  url:   /transporte_alumnos_por_ruta_dia
  param: { module: transporte, action: alumnosPorRutaDia }     
transporte_guardar_alumnos_eventuales:
  url:   /transporte_guardar_alumnos_eventuales
  param: { module: transporte, action: guardarAlumnosEventuales }  
transporte_eliminar_alumno_eventual:
  url:   /transporte_eliminar_alumno_eventual
  param: { module: transporte, action: eliminarAlumnoEventual }  
transporte_guardar_listas_por_ruta:
  url:   /transporte_guardar_listas_por_ruta
  param: { module: transporte, action: guardarListasPorRuta } 
transporte_verificar_guardado:
  url:   /transporte_verificar_guardado
  param: { module: transporte, action: verificaGuardado } 
transporte_imprimir_rutas_alumnos:
  url:   /transporte_imprimir_rutas_alumnos
  param: { module: transporte, action: imprimirRutasAlumnos } 
transporte_cambiar_estatus_alumno_lista_ruta:
  url:   /transporte_cambiar_estatus_alumno_lista_ruta
  param: { module: transporte, action: cambiarEstatusAlumnoListaRuta } 


  
#Fin TRANSPORTE

##Consultas
filtros_ciclos:
  url:   /filtros-ciclos
  param: { module: consultas, action: getCiclosEscolares }  
filtros_grados:
  url:   /filtros-grados
  param: { module: consultas, action: getGradosByCiclo } 
filtros_grupos:
  url:   /filtros-grupos
  param: { module: consultas, action: getGruposByGrado } 
filtros_alumnos:
  url:   /filtros-alumnos
  param: { module: consultas, action: filtrosAlumnos }   
  
#PAGOS
pagos_pagar_servicio:
  url:   /pagos_pagar_servicio
  param: { module: pagos, action: pagarServicio } 
pagos_pagar_servicio_cliente:
  url:   /pagos_pagar_servicio_cliente
  param: { module: pagos, action: pagarServicioCliente } 
pagos_servicios_pagando_alumno:
  url:   /pagos_servicios_pagando_alumno
  param: { module: pagos, action: serviciosPagandoAlumno } 
pagos_pagos_servicios_alumno:
  url:   /pagos_pagos_servicios_alumno
  param: { module: pagos, action: pagoServiciosAlumno } 
pagos_detalles_pagos_servicio_cliente:
  url:   /pagos_detalles_pagos_servicio_cliente
  param: { module: pagos, action: detallesPagosServicioCliente } 
pagos_servicios_pagando_cliente:
  url:   /pagos_servicios_pagando_cliente
  param: { module: pagos, action: serviciosPagandoCliente } 
pagos_pagos_servicios_cliente:
  url:   /pagos_pagos_servicios_cliente
  param: { module: pagos, action: pagoServiciosCliente }   
pagos_imprimir_ticket:
  url:   /pagos_imprimir_ticket
  param: { module: pagos, action: imprimirTicket }   
pagos_estado_cuenta_alumno:
  url:   /pagos_estado_cuenta_alumno
  param: { module: pagos, action: estadoCuentaAlumno } 
pagos_estado_cuenta_cliente:
  url:   /pagos_estado_cuenta_cliente
  param: { module: pagos, action: estadoCuentaCliente }  
pagos_movimientos_caja:
  url:   /pagos_movimientos_caja
  param: { module: pagos, action: movimientosCaja }  
pagos_listado_movimientos_caja:
  url:   /pagos_listado_movimientos_caja
  param: { module: pagos, action: listadoMovimientosCaja }  
pagos_listado_movimientos_caja_imprimir:
  url:   /pagos_listado_movimientos_caja_imprimir
  param: { module: pagos, action: listadoMovimientosCajaImprimir } 
pagos_eliminar_pagos:
  url:   /pagos_eliminar_pagos
  param: { module: pagos, action: eliminarPagos } 
pagos_historial_pagos:
  url:   /pagos_historial_pagos
  param: { module: pagos, action: historialPagos }  
  


#Fin pagos

#Estado de cuenta
estado_cuenta_servicios_estatus:
  url:   /estado_cuenta_servicios_estatus
  param: { module: estadoCuenta, action: serviciosEstatus }   
estado_cuenta_asignados_a_servicio:
  url:   /estado_cuenta_asignados_a_servicio
  param: { module: estadoCuenta, action: asignadosAServicio }   
estado_cuenta_asignados_a_servicio_agrupado:
  url:   /estado_cuenta_asignados_a_servicio_agrupado
  param: { module: estadoCuenta, action: asignadosAServicioAgrupado } 
estado_cuenta_servicios_dias_mora:
  url:   /estado_cuenta_servicios_dias_mora
  param: { module: estadoCuenta, action: serviciosDiasMora }
estado_cuenta_listado_dias_mora:
  url:   /estado_cuenta_listado_dias_mora
  param: { module: estadoCuenta, action: listadoDiasMora } 
estado_cuenta_servicios_activos_alumnos:
  url:   /estado_cuenta_servicios_activos_alumnos
  param: { module: estadoCuenta, action: serviciosActivosAlumnos }   
estado_cuenta_servicios_activos_alumnos_lista:
  url:   /estado_cuenta_servicios_activos_alumnos_lista
  param: { module: estadoCuenta, action: serviciosActivosAlumnosLista }     
estado_cuenta_ingresos_egresos:
  url:   /estado_cuenta_ingresos_egresos
  param: { module: estadoCuenta, action: ingresosEgresos }  
estado_cuenta_ingresos_egresos_imprimir:
  url:   /estado_cuenta_ingresos_egresos_imprimir
  param: { module: estadoCuenta, action: ingresosEgresosImprimir }
estado_cuenta_asignados_a_servicio_imprimir:
  url:   /estado_cuenta_asignados_a_servicio_imprimir
  param: { module: estadoCuenta, action: asignadosAServicioImprimir }
estado_cuenta_asignados_a_servicio_agrupado_imprimir:
  url:   /estado_cuenta_asignados_a_servicio_agrupado_imprimir
  param: { module: estadoCuenta, action: asignadosAServicioAgrupadoImprimir }
estado_cuenta_listado_dias_mora_imprimir:
  url:   /estado_cuenta_listado_dias_mora_imprimir
  param: { module: estadoCuenta, action: listadoDiasMoraImprimir } 
  
   
  
  
#fin estado de cuenta


#SEGURIDAD  
signin:
  url:   /signin
  param: { module: acceso, action: index }    
signout:
  url:   /signout
  param: { module: acceso, action: signout } 
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*