# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            9bd135f597dbf56734ecf47dc6fbc975d2fde1b0

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    use_database:           true
    charset:                iso-8859-1 
    enabled_modules:        [default]
    default_culture:        es 
    logging_enabled:        true
    etag:                   true
  .actions:
    error_404_module:       static   # To be called when a 404 error is raised
    error_404_action:       error404  # Or when the requested URL doesn't match any route
    module_disabled_module: static
    module_disabled_action: disabled
    login_module:           acceso
    login_action:           index
    secure_module:          acceso
    secure_action:          secure