<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/07/06 07:14:37

return array(
'default' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cajab',
  'username' => 'root',
  'password' => NULL,
  'name' => 'default',
)),

'instituto' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=centroeducativooriente.com;dbname=centrof3_io',
  'username' => 'centrof3_view',
  'password' => 'vista#43.Si',
  'name' => 'instituto',
)),);
