<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/06/07 04:49:43
sfConfig::add(array(
  'sf_error_404_module' => 'static',
  'sf_error_404_action' => 'error404',
  'sf_login_module' => 'acceso',
  'sf_login_action' => 'index',
  'sf_secure_module' => 'acceso',
  'sf_secure_action' => 'secure',
  'sf_module_disabled_module' => 'static',
  'sf_module_disabled_action' => 'disabled',
  'sf_use_database' => true,
  'sf_i18n' => false,
  'sf_compressed' => false,
  'sf_check_lock' => false,
  'sf_csrf_secret' => '9bd135f597dbf56734ecf47dc6fbc975d2fde1b0',
  'sf_escaping_strategy' => true,
  'sf_escaping_method' => 'ESC_SPECIALCHARS',
  'sf_no_script_name' => false,
  'sf_cache' => false,
  'sf_etag' => false,
  'sf_web_debug' => true,
  'sf_error_reporting' => 32767,
  'sf_file_link_format' => NULL,
  'sf_admin_web_dir' => '/sf/sf_admin',
  'sf_web_debug_web_dir' => '/sf/sf_web_debug',
  'sf_standard_helpers' => array (
  0 => 'Partial',
  1 => 'Cache',
),
  'sf_enabled_modules' => array (
  0 => 'default',
),
  'sf_charset' => 'iso-8859-1',
  'sf_logging_enabled' => true,
  'sf_default_culture' => 'es',
));
