all:
  layout: menu
serviciosSuccess:
  javascripts: [moment.min.js,servicios.js]
asignarServiciosSuccess:
  javascripts: [moment.min.js,asignarServicios.js]
asignarAlumnoServicioSuccess:
  javascripts: [moment.min.js,asignarAlumnoServicio.js]
  
