# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  default:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=cajab
      username: root
      password: 
      encoding: Latin1
  instituto:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=centroeducativooriente.com;dbname=centrof3_io
      username: centrof3_view
      password: vista#43.Si
      encoding:  Latin1
      #dsn:     mysql:host=localhost;dbname=clubdem4_cajab
      #username: clubdem4_cajabus
      #password: C4J4B0R13NT3  